# Session 10: Missing Values and Duplicates

## Purpose

This notebook checks the dataset for missing values and duplicate rows before preprocessing and model development.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/student-mat.csv", sep=";")

print("Dataset loaded successfully.")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully.
Shape: (395, 33)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

## Check Missing Values Per Column

In [4]:
print("Missing per column:")
print(df.isna().sum())

Missing per column:
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

## Check Total Missing Values

In [5]:
total_missing = df.isna().sum().sum()

print("Total missing values:", total_missing)

Total missing values: 0

## Missing Value Summary Table

In [6]:
missing_summary = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isna().sum().values,
    "Missing_Percent": (df.isna().mean().values * 100).round(2)
})

missing_summary

        Column  Missing_Count  Missing_Percent
0       school              0              0.0
1          sex              0              0.0
2          age              0              0.0
3      address              0              0.0
4      famsize              0              0.0
5      Pstatus              0              0.0
6         Medu              0              0.0
7         Fedu              0              0.0
8         Mjob              0              0.0
9         Fjob              0              0.0
10      reason              0              0.0
11    guardian              0              0.0
12  traveltime              0              0.0
13   studytime              0              0.0
14    failures              0              0.0
15   schoolsup              0              0.0
16      famsup              0              0.0
17        paid              0              0.0
18  activities              0              0.0
19     nursery              0              0.0
20      higher              0              0.0
21    internet              0              0.0
22    romantic              0              0.0
23      famrel              0              0.0
24    freetime              0              0.0
25       goout              0              0.0
26        Dalc              0              0.0
27        Walc              0              0.0
28      health              0              0.0
29    absences              0              0.0
30          G1              0              0.0
31          G2              0              0.0
32          G3              0              0.0

## Prompt-Engineered Explanation Result

The dataset was checked for missing values and duplicate rows before preprocessing and model development.

The missing-value check showed that all columns have zero missing values.

The duplicate-row check also showed zero duplicate rows.

Because every column has zero missing values, imputation is not needed. Since the dataset is already complete, adding imputed values could introduce unnecessary artificial information.

Because the duplicate-row count is zero, no rows need to be removed.

## Recommendation

No cleaning action is required for missing values or duplicate rows at this stage. The dataset can move forward to preprocessing and feature engineering.

## Reflection Question

### Question

Why is documenting "no cleaning needed" just as important as documenting cleaning steps?

### Answer

Documenting "no cleaning needed" is important because it proves that the data-quality check was completed.

It shows that missing values and duplicate rows were examined, not ignored.

Since the dataset had no missing values and no duplicate rows, no imputation or duplicate removal was required.

Recording this decision makes the project more transparent, reproducible, and trustworthy.

In [7]:
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [8]:
cat_cols = df.select_dtypes(include="object").columns.tolist()

print("Number of categorical columns:", len(cat_cols))
print("Categorical columns:", cat_cols)

for c in cat_cols:
    unique_values = df[c].dropna().unique()

    print("\n" + "=" * 80)
    print("Column:", c)
    print("Number of unique values:", df[c].nunique(dropna=False))
    print("First 10 unique values:", unique_values[:10])

Number of categorical columns: 17
Categorical columns: ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

================================================================================
Column: school
Number of unique values: 2
First 10 unique values: ['GP' 'MS']

================================================================================
Column: sex
Number of unique values: 2
First 10 unique values: ['F' 'M']

================================================================================
Column: address
Number of unique values: 2
First 10 unique values: ['U' 'R']

================================================================================
Column: famsize
Number of unique values: 2
First 10 unique values: ['GT3' 'LE3']

================================================================================
Column: Pstatus
Number of unique values: 2
First 10 unique values: ['A' 'T']

================================================================================
Column: Mjob
Number of unique values: 5
First 10 unique values: ['at_home' 'health' 'other' 'services' 'teacher']

================================================================================
Column: Fjob
Number of unique values: 5
First 10 unique values: ['teacher' 'other' 'services' 'health' 'at_home']

================================================================================
Column: reason
Number of unique values: 4
First 10 unique values: ['course' 'other' 'home' 'reputation']

================================================================================
Column: guardian
Number of unique values: 3
First 10 unique values: ['mother' 'father' 'other']

================================================================================
Column: schoolsup
Number of unique values: 2
First 10 unique values: ['yes' 'no']

================================================================================
Column: famsup
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: paid
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: activities
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: nursery
Number of unique values: 2
First 10 unique values: ['yes' 'no']

================================================================================
Column: higher
Number of unique values: 2
First 10 unique values: ['yes' 'no']

================================================================================
Column: internet
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: romantic
Number of unique values: 2
First 10 unique values: ['no' 'yes']

In [9]:
# Session 11: List categorical columns

cat_cols = df.select_dtypes(include="object").columns.tolist()

print("Number of categorical columns:", len(cat_cols))
print("Categorical columns:", cat_cols)

for c in cat_cols:
    unique_values = df[c].dropna().unique()

    print("\n" + "=" * 80)
    print("Column:", c)
    print("Number of unique values:", df[c].nunique(dropna=False))
    print("First 10 unique values:", unique_values[:10])

Number of categorical columns: 17
Categorical columns: ['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob', 'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery', 'higher', 'internet', 'romantic']

================================================================================
Column: school
Number of unique values: 2
First 10 unique values: ['GP' 'MS']

================================================================================
Column: sex
Number of unique values: 2
First 10 unique values: ['F' 'M']

================================================================================
Column: address
Number of unique values: 2
First 10 unique values: ['U' 'R']

================================================================================
Column: famsize
Number of unique values: 2
First 10 unique values: ['GT3' 'LE3']

================================================================================
Column: Pstatus
Number of unique values: 2
First 10 unique values: ['A' 'T']

================================================================================
Column: Mjob
Number of unique values: 5
First 10 unique values: ['at_home' 'health' 'other' 'services' 'teacher']

================================================================================
Column: Fjob
Number of unique values: 5
First 10 unique values: ['teacher' 'other' 'services' 'health' 'at_home']

================================================================================
Column: reason
Number of unique values: 4
First 10 unique values: ['course' 'other' 'home' 'reputation']

================================================================================
Column: guardian
Number of unique values: 3
First 10 unique values: ['mother' 'father' 'other']

================================================================================
Column: schoolsup
Number of unique values: 2
First 10 unique values: ['yes' 'no']

================================================================================
Column: famsup
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: paid
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: activities
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: nursery
Number of unique values: 2
First 10 unique values: ['yes' 'no']

================================================================================
Column: higher
Number of unique values: 2
First 10 unique values: ['yes' 'no']

================================================================================
Column: internet
Number of unique values: 2
First 10 unique values: ['no' 'yes']

================================================================================
Column: romantic
Number of unique values: 2
First 10 unique values: ['no' 'yes']

In [10]:
import pandas as pd

cat_summary = []

for c in cat_cols:
    cat_summary.append({
        "column": c,
        "unique_count": df[c].nunique(dropna=False),
        "example_values": list(df[c].dropna().unique()[:10])
    })

cat_summary_df = pd.DataFrame(cat_summary)

cat_summary_df

        column  unique_count                               example_values
0       school             2                                     [GP, MS]
1          sex             2                                       [F, M]
2      address             2                                       [U, R]
3      famsize             2                                   [GT3, LE3]
4      Pstatus             2                                       [A, T]
5         Mjob             5  [at_home, health, other, services, teacher]
6         Fjob             5  [teacher, other, services, health, at_home]
7       reason             4            [course, other, home, reputation]
8     guardian             3                      [mother, father, other]
9    schoolsup             2                                    [yes, no]
10      famsup             2                                    [no, yes]
11        paid             2                                    [no, yes]
12  activities             2                                    [no, yes]
13     nursery             2                                    [yes, no]
14      higher             2                                    [yes, no]
15    internet             2                                    [no, yes]
16    romantic             2                                    [no, yes]